---
# Source: hperm/templates/developer.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hperm-sa-developer-dev.test1
  namespace: hperm
---
# Source: hperm/templates/developer.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: hperm-role-developer-default-dev.test1
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
# Source: hperm/templates/developer.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: hperm-rb-developer-default-dev.test1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hperm-role-developer-default-dev.test1
subjects:
- kind: ServiceAccount
  name: hperm-sa-developer-dev.test1
  namespace: hperm
